data <- read.table('./household_power_consumption.txt',header=TRUE,sep=";",na.strings = "?")
data$Date<-as.Date(data$Date,format="%d/%m/%Y")
dataused<-subset(data,Date>='2007-02-01' & Date<='2007-02-02')
dataused$Timenew<-as.POSIXct(paste(dataused$Date,dataused$Time), format="%Y-%m-%d %H:%M:%S")
png(file='plot3.png', width = 480, height = 480, units = "px")
plot(dataused$Timenew,dataused$Sub_metering_1,type = "l", xlab="",ylab = "Energy sub metering",col="black")
lines(dataused$Timenew,dataused$Sub_metering_2, type = "l",col="red")
lines(dataused$Timenew,dataused$Sub_metering_3, type = "l",col="blue")
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lwd=1, col = c("black","red","blue"))
dev.off()