data <- read.table('./household_power_consumption.txt',header=TRUE,sep=";",na.strings = "?")
data$Date<-as.Date(data$Date,format="%d/%m/%Y")
dataused<-subset(data,Date>='2007-02-01' & Date<='2007-02-02')
dataused$Timenew<-as.POSIXct(paste(dataused$Date,dataused$Time), format="%Y-%m-%d %H:%M:%S")
png(file='plot2.png', width = 480, height = 480, units = "px")
plot(dataused$Timenew,dataused$Global_active_power,type = "l", xlab="",ylab = "Global Active Power (kilowatts)")
dev.off()